@startuml

start
note right
配列を照準にソートする
end note

:「配列」をセット;
:「配列長」を取得;

:「底値」に0を入れる;

:「探索対象」に「底値」を入れる;

partition この枠内をループする {
    :canvasに配列を描画;
    if(「配列[探索対象1]」>「配列[探索対象2]」?) then (yes)
         :「配列[探索対象]」と「配列[探索対象+1]」を交換;
         :canvasに交換のアニメーションを描画;
    endif
    :「探索対象」++;
    if (「探索対象」 == 「配列長」？) then (yes)
        :「底値」++;
        :「探索対象」に「底値」を入れる;
    endif
    if (「底値」 == 「配列長」？) then (yes)
        :ループから抜ける;
    endif
}
:canvasに終了の旨を出力;
stop
@enduml

